version: '4.17.0'

services:
  authentic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    commend: 'php artisan serve --host=0.0.0.0'

    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my-laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=pharmacy
      - MYSQL_USER=my_laravel_user
      - MYSQL_PASSWORD=my_laravel_password
      - MYSQL_ROOT_PASSWORD=my_laravel_root_password
    ports:
      - '3306:3306'
    volumes:
      - ./storage/dbdata:/var/lib/mysql

